# Generated by Django 2.1.5 on 2019-02-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20190112_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_appointment',
            name='id_appointment',
        ),
        migrations.RemoveField(
            model_name='service_appointment',
            name='id_service',
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tipo',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Service'),
        ),
        migrations.DeleteModel(
            name='Service_Appointment',
        ),
    ]
