# Generated by Django 2.1.5 on 2019-02-03 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0003_auto_20190202_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_client',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='id_client',
        ),
        migrations.AddField(
            model_name='appointment',
            name='id_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
